-- FUNCIONES DE AGREGADO O AGRUPAMIENTO (OBTENEMOS UN RESUMEN)
-- TRABAJAN CON CUALQUIER TIPO DE DATO
COUNT(nom_columna) => CONTAR FILAS
MIN(nom_columna) => MENOR O PRIMER VALOR DE LA COLUMNA
MAX(nom_columna) => MAYOR O ULTIMO VALOR DE LA COLUMNA
-- TRABAJAN SOLO CON LOS TIPOS NUMERICOS
AVG(nom_columna) => PROMEDIO DE LA COLUMNA
SUM(nom_columna) => SUMA O ACUMULADO DE LA COLUMNA

-- OBSERVACION 1: CUANDO EN LA LISTA DE COLUMNAS DEL SELECT SOLO APARECEN
-- FUNCIONES DE AGREGADO, NO ES NECESARIO AGRUPAR (NO UTILIZAR LA CLAUSULA GROUP BY)
SELECT  COUNT(P.IDPRODUCTO) AS CANT_PRODUCTOS, 
        COUNT(*) AS CANT_PRODUCTOS_2,
        MIN(P.PRECIO) AS MENOR_PRECIO, 
        MAX(P.PRECIO) AS MAYOR_PRECIO
FROM PRODUCTOS P;

SELECT * FROM PRODUCTOS ORDER BY STOCK ASC;

SELECT MIN(P.NOMBREPROD) AS PRIMER_NOMBRE, 
       MAX(P.NOMBREPROD) AS ULTIMO_NOMBRE,
       ROUND(AVG(P.STOCK),2) AS PROMEDIO_STOCK, 
       SUM(P.PRECIO*P.STOCK) AS STOCK_VALORIZADO 
FROM PRODUCTOS P;

-- OBSERVACION 2: CUANDO EN LA LISTA DE COLUMNAS DEL SELECT APARECEN COLUMNAS Y 
-- COLUMNAS CON FUNCIONES DE AGREGADO, ES NECESARIO AGRUPAR POR LAS COLUMNAS QUE NO
-- SE ENCUENTREN DENTRO DE UNA FUNCION DE AGREGADO (UTILIZAR LA CLAUSULA GROUP BY)
SELECT IDCATEGORIA, 
       COUNT(IDPRODUCTO) AS CANT_PROD_CATEGORIA 
FROM PRODUCTOS
GROUP BY IDCATEGORIA
   ORDER BY IDCATEGORIA ASC;

-- QUE APAREZCA EL NOMBRE DE LA CATEGORIA TAMBIEN
-- SOLUCION: ANTIGUA
SELECT P.IDCATEGORIA, C.NOMBRECAT,
       COUNT(IDPRODUCTO) AS CANT_PROD_CATEGORIA 
FROM PRODUCTOS P, CATEGORIAS C
WHERE P.IDCATEGORIA=C.IDCATEGORIA
GROUP BY P.IDCATEGORIA, C.NOMBRECAT
   ORDER BY P.IDCATEGORIA ASC;
   
-- SOLUCION: INNER JOIN   
SELECT P.IDCATEGORIA, C.NOMBRECAT,
       COUNT(IDPRODUCTO) AS CANT_PROD_CATEGORIA 
FROM PRODUCTOS P INNER JOIN CATEGORIAS C
  ON P.IDCATEGORIA=C.IDCATEGORIA
GROUP BY P.IDCATEGORIA, C.NOMBRECAT
   ORDER BY P.IDCATEGORIA ASC;
   
-- SOLUCION: NATURAL JOIN   
SELECT IDCATEGORIA, NOMBRECAT,
       COUNT(IDPRODUCTO) AS CANT_PROD_CATEGORIA 
FROM PRODUCTOS P NATURAL JOIN CATEGORIAS C
GROUP BY IDCATEGORIA, NOMBRECAT
   ORDER BY IDCATEGORIA ASC;

-- SOLUCION: JOIN USING(CAMPO_CLAVE)   
SELECT IDCATEGORIA, C.NOMBRECAT,
       COUNT(IDPRODUCTO) AS CANT_PROD_CATEGORIA 
FROM PRODUCTOS P JOIN CATEGORIAS C USING(IDCATEGORIA) 
GROUP BY IDCATEGORIA, C.NOMBRECAT
   ORDER BY IDCATEGORIA ASC;
   