SELECT * FROM CAT;

-- CURSORES
-- IMPLICITO: AQUEL QUE SOLO MANEJA UNA SOLA FILA O VALORES. 
-- SELECT COLUMNAS INTO VALORES FROM TABLA
-- INSERT, UPDATE O DELETE QUE SOLO AFECTE A UN REGISTRO

-- EXPLICITO: AQUEL QUE MANIPULA VARIAS FILAS
-- "PASOS" PARA USAR UN CURSOR
-- DECLARAR EL CURSOR
-- ABRIR EL CURSOR (OPEN)
-- RECUPERAR LA FILA DESDE EL CURSOR (FETCH)
-- MANIPULAR DEL CURSOR (PARA LA SALIDA O CONTINUACION DE LA LECTURA 
-- DEL CURSOR)
-- CERRAR EL CURSOR (CLOSE)

-- LISTAR LOS CLIENTES USANDO UN CURSOR, MOSTRANDO EL CODIGO, NOMBRE Y
-- SU TELEFONO (LOOP)
-- CURSOR NOM_CURSOR IS SELECT ....;
-- NOM_CURSOR%NOTFOUND => CUANDO NO SE TIENE MAS FILAS POR LEER
-- NOM_CURSOR%FOUND => CUANDO SE TIENE MAS FILAS POR LEER

-- RPAD(CAMPO, TAMAÑO, CARACTER_RELLENO_DERECHA)
-- LPAD(CAMPO, TAMAÑO, CARACTER_RELLENO_IZQUIERDA)
SELECT LPAD('ORACLE', 15, ' ') FROM DUAL;
SELECT RPAD('ORACLE', 15, '*') FROM DUAL;

SET SERVEROUTPUT ON;

-----------------
-- LOOP
-----------------
DECLARE
  CURSOR CLI IS SELECT IDCLIENTE, NOMBRECLI, TELEFONO FROM CLIENTES
  XIDCLIENTE CHAR(5);
  XNOMBRE VARCHAR2(50);
  XTELEFONO VARCHAR2(25);
BEGIN
  OPEN CLI;
  -- COMIENZO DEL BUCLE LOOP
  LOOP
    -- RECUPERAMOS (LEER) UNA FILA DEL CURSOR Y ASIGNAMOS LOS VALORES
    -- A LA VARIABLES (LOOP Y WHILE)
    FETCH CLI INTO XIDCLIENTE, XNOMBRE, XTELEFONO;
    -- SALIMOS DEL BUCLE CUANDO EL CURSOR NO PUEDA LEER MAS FILAS
    EXIT WHEN CLI%NOTFOUND;
    -- IMPRIMIR LOS RESULTADOS
    DBMS_OUTPUT.PUT_LINE(RPAD(XIDCLIENTE,10,' ')||
                         RPAD(XNOMBRE,40,' ')||
                         LPAD(XTELEFONO,15,'*'));
  END LOOP;
  -- CERRAR EL CURSOR
  CLOSE CLI;
END;

--------------
-- WHILE
--------------
DECLARE
  --
  XCODCAT NUMBER;
  CURSOR PROD IS SELECT IDPRODUCTO, NOMBREPROD, PRECIO, STOCK FROM PRODUCTOS
                    WHERE IDCATEGORIA=XCODCAT;
  --
  XIDPRODUCTO PRODUCTOS.IDPRODUCTO%TYPE; -- NUMBER;
  XNOMBRE PRODUCTOS.NOMBREPROD%TYPE; -- VARCHAR2(50)
  XPRECIO PRODUCTOS.PRECIO%TYPE; -- NUMBER
  XSTOCK  PRODUCTOS.STOCK%TYPE;  -- NUMBER
  XCONTA  NUMBER:=0;
  XNOMCAT CATEGORIAS.NOMBRE%TYPE;
BEGIN
  -- 
  XCODCAT:=&ID_CATEGORIA;
  --
  SELECT NOMBRECAT INTO XNOMCAT FROM CATEGORIAS WHERE IDCATEGORIA=XCODCAT;
  --
  OPEN PROD;
  -- RECUPERAMOS (LEER) UNA FILA DEL CURSOR Y ASIGNAMOS LOS VALORES
  -- A LA VARIABLES (LOOP Y WHILE)
  FETCH PROD INTO XIDPRODUCTO, XNOMBRE, XPRECIO, XSTOCK;
  -- COMIENZO DEL BUCLE WHILE
  WHILE PROD%FOUND LOOP
    XCONTA:=XCONTA+1;
    -- IMPRIMIR LOS RESULTADOS
    DBMS_OUTPUT.PUT_LINE(RPAD(XIDPRODUCTO,5,' ')||
                         RPAD(XNOMBRE,40,' ')||
                         RPAD(XPRECIO,10,' ')||
                         LPAD(XSTOCK,10,'*'));
    -- RECUPERAMOS (LEER) UNA FILA DEL CURSOR Y ASIGNAMOS LOS VALORES
    -- A LA VARIABLES (LOOP Y WHILE)
    FETCH PROD INTO XIDPRODUCTO, XNOMBRE, XPRECIO, XSTOCK;                   
  END LOOP;
  -- CERRAR EL CURSOR
  CLOSE PROD;
  --
  DBMS_OUTPUT.PUT_LINE('CANTIDAD DE PRODUCTOS: '||XCONTA);
  DBMS_OUTPUT.PUT_LINE('DE LA CATEGORIA: '||XNOMCAT);
END;


------------
-- FOR
------------
DECLARE
   XCODCAT NUMBER;
   CURSOR PROD(CODIGO NUMBER) 
      IS SELECT * FROM PRODUCTOS WHERE IDCATEGORIA=CODIGO;
   -- FILA PROD%ROWTYPE; -- VARIABLE DE LA FILA DE UN CURSOR
   XCONTA NUMBER:=0;
   XNOMCAT VARCHAR2(20);
BEGIN
  XCODCAT:=&ID_CATEGORIA;
  SELECT NOMBRECAT INTO XNOMCAT FROM CATEGORIAS WHERE IDCATEGORIA=XCODCAT; 
  --
  FOR FILA IN PROD(XCODCAT) LOOP
    -- IMPRIMIR LOS RESULTADOS
    DBMS_OUTPUT.PUT_LINE(RPAD(FILA.IDPRODUCTO,5,' ')||
                         RPAD(FILA.NOMBREPROD,40,' ')||
                         RPAD(FILA.PRECIO,10,' ')||
                         LPAD(FILA.STOCK,10,'*'));
    --
    XCONTA:=XCONTA+1;
  END LOOP;
  --
  DBMS_OUTPUT.PUT_LINE('CANTIDAD DE PRODUCTOS: '||XCONTA);
  DBMS_OUTPUT.PUT_LINE('DE LA CATEGORIA: '||XNOMCAT);  
END;



-- loop usando variable_cursor%rowtype
DECLARE
  CURSOR CLI IS SELECT IDCLIENTE, NOMBRECLI, TELEFONO FROM CLIENTES;
  FILA CLI%ROWTYPE;  -- FILA DE UN CURSOR
BEGIN
  OPEN CLI;
  -- COMIENZO DEL BUCLE LOOP
  LOOP
    -- RECUPERAMOS (LEER) UNA FILA DEL CURSOR Y ASIGNAMOS LOS VALORES
    -- A LA VARIABLES (LOOP Y WHILE)
    FETCH CLI INTO FILA;
    -- SALIMOS DEL BUCLE CUANDO EL CURSOR NO PUEDA LEER MAS FILAS
    EXIT WHEN CLI%NOTFOUND;
    -- IMPRIMIR LOS RESULTADOS
    DBMS_OUTPUT.PUT_LINE(RPAD(FILA.IDCLIENTE,10,' ')||
                         RPAD(FILA.NOMBRECLI,40,' ')||
                         LPAD(FILA.TELEFONO,15,'*'));
  END LOOP;
  -- CERRAR EL CURSOR
  CLOSE CLI;
END;




-- while usando variable_cursor%rowtype
DECLARE
  --
  XCODCAT NUMBER;
  CURSOR PROD IS SELECT IDPRODUCTO, NOMBREPROD, PRECIO, STOCK FROM PRODUCTOS
                    WHERE IDCATEGORIA=XCODCAT;
  --
  FILA  PROD%ROWTYPE;  -- FILA DEL CURSOR PROD
  XCONTA  NUMBER:=0;
  XNOMCAT CATEGORIAS.NOMBRECAT%TYPE;
BEGIN
  -- 
  XCODCAT:=&ID_CATEGORIA;
  --
  SELECT NOMBRECAT INTO XNOMCAT FROM CATEGORIAS WHERE IDCATEGORIA=XCODCAT;
  --
  OPEN PROD;
  -- RECUPERAMOS (LEER) UNA FILA DEL CURSOR Y ASIGNAMOS LOS VALORES
  -- A LA VARIABLES (LOOP Y WHILE)
  FETCH PROD INTO FILA;
  -- COMIENZO DEL BUCLE WHILE
  WHILE PROD%FOUND LOOP
    XCONTA:=XCONTA+1;
    -- IMPRIMIR LOS RESULTADOS
    DBMS_OUTPUT.PUT_LINE(RPAD(FILA.IDPRODUCTO,5,' ')||
                         RPAD(FILA.NOMBREPROD,40,' ')||
                         RPAD(FILA.PRECIO,10,' ')||
                         LPAD(FILA.STOCK,10,'*'));
    -- RECUPERAMOS (LEER) UNA FILA DEL CURSOR Y ASIGNAMOS LOS VALORES
    -- A LA VARIABLES (LOOP Y WHILE)
    FETCH PROD INTO FILA;                   
  END LOOP;
  -- CERRAR EL CURSOR
  CLOSE PROD;
  --
  DBMS_OUTPUT.PUT_LINE('CANTIDAD DE PRODUCTOS: '||XCONTA);
  DBMS_OUTPUT.PUT_LINE('DE LA CATEGORIA: '||XNOMCAT);
END;


--
DECLARE
  CURSOR C1 IS
    SELECT  C.NOMBRECAT, COUNT(*) AS CANTIDAD_PROD, 
              SUM(P.PRECIO) AS SUMA_PRECIOS_PROD
        FROM CATEGORIAS C INNER JOIN PRODUCTOS P
          ON C.IDCATEGORIA = P.IDCATEGORIA
            GROUP BY C.NOMBRECAT;
  XSUMA NUMBER:=0;          
BEGIN
  FOR FILA IN C1 LOOP
    DBMS_OUTPUT.PUT_LINE(RPAD(FILA.NOMBRECAT,40,' ')||
                         LPAD(FILA.CANTIDAD_PROD,6,' ')||
                         LPAD(FILA.SUMA_PRECIOS_PROD,8,' '));
    --
    XSUMA:=XSUMA+FILA.SUMA_PRECIOS_PROD;
  END LOOP;
  --
  DBMS_OUTPUT.PUT_LINE('SUMA DE LOS PRECIOS DE TODAS LAS CATEGORIAS: '||
                             TO_CHAR(XSUMA,'99,999.99'));
END;



